# ================================
# ETAPA 1: BUILD
# ================================
FROM node:22-alpine AS builder

WORKDIR /app

RUN apk update && apk upgrade --no-cache

ARG API_URL
ENV API_URL=$API_URL

COPY package.json package-lock.json ./

# Instalar TODAS las dependencias (incluye Webpack y Babel)
RUN npm ci && npm cache clean --force

COPY . .

# Construir Webpack
RUN npm run build

# ================================
# ETAPA 2: RUNTIME (NGINX UNPRIVILEGED)
# ================================
FROM nginxinc/nginx-unprivileged:1.27-alpine

RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
