apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:4b8d4be0da0410687d2107fca910f35d610715c4b3c9ed4b58ab99f91486513d
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:80badd768925042709e017a1706b24583d6c29dd6c578e154d53f79f271fcd54
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
