apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../monitoring/base


images:
- digest: sha256:b86a6fa73edf2fc04b88c7c5858e7a1c3a3cc18596ea9b374348a916b99d7147
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:e6e3357f7b6f4c2299d1884c627d64068d1a212c55f763b97d8d1e1943f2b8a5
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
