apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:e7facf1faed8396f3346d9f048f296a98ba0e8fc7c9cbe36b4bbe78b7b0b4ec4
  name: backend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/backend
- digest: sha256:ddc03c54ec26352ac1bb5098b1604717fd18de887404971082ca59458510c0ce
  name: frontend
  newName: ghcr.io/jsaenz72/tfm-devops-app-demo-node-react/frontend
