# k8s/base/ghcr-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: demo-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_DEL_DOCKERCONFIG>